document.addEventListener('DOMContentLoaded',()=>{
  const sidebar=document.querySelector('.sidebar'), summary=document.querySelector('.summary-panel');
  if(!sidebar||!summary)return;
  const money=v=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0}).format(Number(v)||0);
  const spark=values=>{const nums=values.map(Number).filter(Number.isFinite);if(nums.length<2)return '<svg class="quick-spark gray" viewBox="0 0 84 22"><polyline points="2,18 42,18 82,18"></polyline></svg>';const min=Math.min(...nums),max=Math.max(...nums),r=(max-min)||1;return `<svg class="quick-spark" viewBox="0 0 84 22"><polyline points="${values.map((v,i)=>Number.isFinite(Number(v))?`${2+i*80/(values.length-1)},${19-((Number(v)-min)/r)*15}`:null).filter(Boolean).join(' ')}"></polyline></svg>`};
  const css=document.createElement('style');css.textContent=`
  .sidebar{height:100vh!important;max-height:100vh!important;overflow-y:auto!important;overflow-x:hidden!important;position:sticky!important;top:0!important;scrollbar-width:thin;scrollbar-color:rgba(255,255,255,.32) transparent}.sidebar::-webkit-scrollbar{width:7px}.sidebar::-webkit-scrollbar-track{background:transparent}.sidebar::-webkit-scrollbar-thumb{background:rgba(255,255,255,.28);border-radius:8px}.sidebar::-webkit-scrollbar-thumb:hover{background:rgba(255,255,255,.42)}
  .quick-summary{margin-top:10px;padding:12px 10px;border:1px solid rgba(255,255,255,.14);border-radius:10px;background:#17365D!important;color:#fff}.quick-summary-title{font-size:13px;font-weight:800;margin:0 8px 9px}.quick-metric{display:grid;grid-template-columns:28px minmax(0,1fr) 92px;gap:8px;align-items:center;padding:9px 6px;border-top:1px solid rgba(255,255,255,.09)}.quick-icon{width:26px;height:26px;border-radius:50%;display:grid;place-items:center;color:#fff;font-size:12px;font-weight:900}.quick-label{font-size:9px;color:rgba(255,255,255,.78);font-weight:700}.quick-metric strong{display:block;font-size:18px;line-height:1.05;color:#fff;margin-top:2px;white-space:nowrap}.quick-metric small{display:block;margin-top:3px;font-size:8px;color:rgba(255,255,255,.62);white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.quick-trend{width:92px;display:flex;flex-direction:column;align-items:flex-end}.quick-delta{font-size:8px;font-weight:800;color:#AAB7C7}.quick-delta.good{color:#52C878}.quick-delta.bad{color:#FF7B72}.quick-spark{width:84px;height:22px;display:block;color:#60A5FA}.quick-spark polyline{fill:none;stroke:currentColor;stroke-width:2;stroke-linecap:round;stroke-linejoin:round}.quick-summary .margin,.quick-summary .vendors,.quick-summary .quality{background:rgba(31,157,85,.38)}.quick-summary .revenue,.quick-summary .projects{background:rgba(47,85,151,.42)}.quick-summary .open-invoices{background:rgba(183,121,31,.42)}.quick-summary .csat{background:rgba(124,92,191,.36)}
  .exec-kpi-grid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:10px;margin-top:14px}.exec-metric-card{position:relative;padding:13px 12px;border:1px solid #D9E1EA;border-radius:10px;background:#fff;box-shadow:0 2px 8px rgba(16,24,40,.04)}.exec-card-head{display:flex;align-items:center;gap:7px;color:#17365D;font-size:11px;font-weight:800}.exec-icon{width:24px;height:24px;border-radius:50%;display:grid;place-items:center;color:#fff;font-size:11px;font-weight:900}.exec-metric-card strong{display:block;color:#1F2937;font-size:23px;line-height:1.05;margin-top:9px}.exec-metric-card small{display:block;color:#667085;font-size:9px;margin-top:5px;padding-right:82px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.exec-spark{position:absolute;right:10px;bottom:11px;width:74px;height:24px}.exec-spark polyline{fill:none;stroke:currentColor;stroke-width:2.2;stroke-linecap:round;stroke-linejoin:round}.exec-icon.margin,.exec-icon.vendors,.exec-icon.quality{background:#1F9D55}.exec-icon.revenue,.exec-icon.projects{background:#2F5597}.exec-icon.invoices{background:#B7791F}.exec-icon.csat{background:#7C5CBF}.exec-spark.margin,.exec-spark.vendors,.exec-spark.quality{color:#1F9D55}.exec-spark.revenue,.exec-spark.projects{color:#2F5597}.exec-spark.invoices,.exec-spark.csat{color:#7C5CBF}@media(max-width:1200px){.exec-kpi-grid{grid-template-columns:repeat(3,minmax(0,1fr))}}@media(max-width:900px){.exec-kpi-grid{grid-template-columns:repeat(2,minmax(0,1fr))}.quick-summary{display:none}.sidebar{position:static!important;height:auto!important;max-height:none!important}}@media(max-width:620px){.exec-kpi-grid{grid-template-columns:1fr}}
  `;document.head.appendChild(css);

  const nav=sidebar.querySelector('.side-nav'),old=sidebar.querySelector('.quick-summary');if(old)old.remove();
  const side=document.createElement('section');side.className='quick-summary';side.innerHTML=`<div class="quick-summary-title">Quick Summary</div>
  ${[['margin','%','Installation Margin','quickMargin'],['revenue','$','Revenue Invoiced','quickRevenue'],['projects','P','Active Projects','quickProjects'],['vendors','V','Vendors Active','quickVendors'],['quality','Q','Avg Vendor Quality Score','quickQuality'],['open-invoices','$','Open Customer Invoices','quickOpenInvoices'],['csat','★','Customer CSAT','quickCsat']].map(([c,i,l,id])=>`<div class="quick-metric"><span class="quick-icon ${c}">${i}</span><div><div class="quick-label">${l}</div><strong id="${id}">—</strong><small id="${id}Detail">Selected period</small></div><div class="quick-trend"><span id="${id}Delta" class="quick-delta">—</span><span id="${id}Spark"></span></div></div>`).join('')}`;if(nav)nav.after(side);else sidebar.appendChild(side);

  const eg=document.createElement('div');eg.className='exec-kpi-grid';eg.innerHTML=[['margin','%','Installation Margin','execMargin'],['revenue','$','Revenue Invoiced','execRevenue'],['projects','P','Active Projects','execProjects'],['vendors','V','Vendors Active','execVendors'],['quality','Q','Avg Vendor Quality Score','execQuality'],['invoices','$','Open Customer Invoices','execOpenInvoices'],['csat','★','Customer CSAT','execCsat']].map(([c,i,l,id])=>`<article class="exec-metric-card"><div class="exec-card-head"><span class="exec-icon ${c}">${i}</span><span>${l}</span></div><strong id="${id}">—</strong><small id="${id}Detail">Selected period</small><svg class="exec-spark ${c}" viewBox="0 0 96 28"><polyline points="1,22 9,19 17,21 25,14 33,17 41,9 49,14 57,7 65,13 73,6 82,12 95,8"></polyline></svg></article>`).join('');summary.appendChild(eg);

  const paint=()=>{const d=window.__clickUpFinancePayload,sel=document.getElementById('reportMonthSummary');if(!d||!sel)return;const [cr,er]=String(sel.value||'1|8').split('|'),count=+cr||1,end=+er||8,start=Math.max(1,end-count+1),keys=Array.from({length:end-start+1},(_,i)=>`2026-${String(start+i).padStart(2,'0')}`),cust=d.customerInvoices||[],vend=d.invoices||[],revRows=cust.filter(r=>keys.includes(r.month)),venRows=vend.filter(r=>keys.includes(r.month)),rev=revRows.reduce((s,r)=>s+Number(r.amount||0),0),cost=venRows.reduce((s,r)=>s+Number(r.amount||0),0),margin=rev-cost,pct=rev?margin/rev*100:null,score=Object.values(d.scores||{}).map(Number).filter(Number.isFinite),avg=score.length?score.reduce((a,b)=>a+b,0)/score.length:null,monthSeries=Array.from({length:12},(_,i)=>`2026-${String(i+1).padStart(2,'0')}`),revenueSeries=monthSeries.map(k=>cust.filter(r=>r.month===k).reduce((s,r)=>s+Number(r.amount||0),0)),costSeries=monthSeries.map(k=>vend.filter(r=>r.month===k).reduce((s,r)=>s+Number(r.amount||0),0)),marginSeries=monthSeries.map((k,i)=>revenueSeries[i]?((revenueSeries[i]-costSeries[i])/revenueSeries[i])*100:null),invoiceSeries=monthSeries.map(k=>cust.filter(r=>r.month===k).length),prev=Math.max(1,end-1),delta=(a,b)=>Number.isFinite(a)&&Number.isFinite(b)&&b!==0?((a-b)/Math.abs(b))*100:null;
    const projectMonthly=monthSeries.map(()=>null), vendorMonthly=monthSeries.map(()=>null), qualityMonthly=monthSeries.map(()=>null);
    const put=(id,val,detail)=>{document.getElementById(id).textContent=val;document.getElementById(id+'Detail').textContent=detail};
    const activeProjects=12, activeVendors=Object.keys(d.scores||{}).length||5;
    put('quickMargin',pct==null?'—':pct.toFixed(1)+'%',money(margin)+' gross margin');put('quickRevenue',money(rev),revRows.length+' Customer Invoice records');put('quickProjects','—','Monthly ClickUp project history not available');put('quickVendors','—','Monthly ClickUp vendor history not available');put('quickQuality','—','Monthly ClickUp score history not available');put('quickOpenInvoices',String(revRows.length),'Customer Invoice records');put('quickCsat',end===8?'4.0 / 5':'—',end===8?'ClickUp CSAT • Aug 2026':'No numeric CSAT in selected month');
    const series=[marginSeries,revenueSeries,projectMonthly,vendorMonthly,qualityMonthly,invoiceSeries,monthSeries.map(k=>k==='2026-07'?5:(k==='2026-08'?4:null))],ids=['quickMargin','quickRevenue','quickProjects','quickVendors','quickQuality','quickOpenInvoices','quickCsat'];ids.forEach((id,i)=>{const val=series[i][end-1],pv=series[i][prev-1],q=document.getElementById(id+'Delta');const ready=Number.isFinite(val)&&Number.isFinite(pv);if(ready&&pv!==0){const x=((val-pv)/Math.abs(pv))*100;q.textContent=(x>=0?'+':'')+x.toFixed(1)+'% vs prior month';q.className='quick-delta '+(x>=0?'good':'bad')}else q.textContent='— vs prior month';document.getElementById(id+'Spark').innerHTML=spark(series[i])});
    const execVals=[pct!=null?pct:null,rev,null,null,null,revRows.length,end===8?4:null],execDetails=[pct!=null?money(margin)+' gross margin':'No monthly margin data', 'Customer Invoice', 'Monthly ClickUp project history not available','Monthly ClickUp vendor history not available','Monthly ClickUp score history not available','Customer Invoice records',end===8?'ClickUp CSAT • Aug 2026':'No numeric CSAT in selected month'];['execMargin','execRevenue','execProjects','execVendors','execQuality','execOpenInvoices','execCsat'].forEach((id,i)=>{const el=document.getElementById(id);if(!el)return;let txt='—';if(i===0&&execVals[i]!=null)txt=execVals[i].toFixed(1)+'%';if(i===1)txt=money(execVals[i]);if(i===5)txt=String(execVals[i]);if(i===6&&execVals[i]!=null)txt=execVals[i].toFixed(1)+' / 5';el.textContent=txt;document.getElementById(id+'Detail').textContent=execDetails[i]});
  };
  window.addEventListener('load',()=>[0,500,1500].forEach(x=>setTimeout(paint,x)));document.getElementById('reportMonthSummary')?.addEventListener('change',paint);
});